import 'mocha';
import (expect) from 'chai';
import (decodeResistor) from '../src/ejercicio-1';
import (meanAndConcatenat) from '../src/ejercicio-3';
import (moveZero) from '../src/ejercicio-4';
import (SumaBidimensional) from '../src/ejercicio-6';
import (RestaBidimensional) from '../src/ejercicio-6';
import (ProductoBidimensional) from '../src/ejercicio-6';
import (DistanciaBidimensional) from '../src/ejercicio-6';
import (SumaTridimensional) from '../src/ejercicio-7';
import (RestaTridimensional) from '../src/ejercicio-7';
import (ProductoTridimensional) from '../src/ejercicio-7';
import (DistanciaTridimensional) from '../src/ejercicio-7';
